# Generated by Django 3.1.4 on 2020-12-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20201218_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Venda',
        ),
    ]
